version: "3.0"

services:

  phpunuhi:
    container_name: phpunuhi
    image: dockware/flex:latest
    volumes:
      - "../:/app"
    working_dir: /app
    environment:
      - PHP_VERSION=8.2
      - XDEBUG_ENABLED=1